services:
  app:
    build: .
    image: knots:latest
    ports:
      - 3000:3000
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - knot_network

  db:
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - container.env
    volumes:
      - ./postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - knot_network

networks:
  knot_network:
    driver: bridge
